name: supabase

services:
  #############################################################################
  # Kong (API Gateway)
  #############################################################################
  kong:
    container_name: supabase-kong
    image: kong:2.8.5
    restart: unless-stopped
    # Publish container ports 8000 and 8443 to host ports 8000 and 8443
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
    volumes:
      - ./volumes/api/kong.yml:/home/kong/temp.yml:ro
    # depends_on:
    #   analytics:
    #     condition: service_healthy
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: "64 160k"
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
      DASHBOARD_USERNAME: supabase
      DASHBOARD_PASSWORD: this_password_is_insecure_and_should_be_updated
    entrypoint: >
      bash -c 'eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'

    x-casaos: # CasaOS specific configuration
      envs:
        - container: KONG_HTTP_PORT
          description:
            en_us: The HTTP port for Kong
            fr_fr: Le port HTTP pour Kong
        - container: KONG_HTTPS_PORT
          description:
            en_us: The HTTPS port for Kong
            fr_fr: Le port HTTPS pour Kong

        - container: SUPABASE_ANON_KEY
          description:
            en_us: The anonymous key for Kong
            fr_fr: La clé anonyme pour Kong
        - container: SUPABASE_SERVICE_KEY
          description:
            en_us: The service role key for Kong
            fr_fr: La clé de rôle de service pour Kong

        - container: DASHBOARD_USERNAME
          description:
            en_us: The username for the dashboard
            fr_fr: Le nom d'utilisateur pour le tableau de bord
        - container: DASHBOARD_PASSWORD
          description:
            en_us: The password for the Kong dashboard
            fr_fr: Le mot de passe pour le tableau de bord de Kong

#############################################################################
# CasaOS AppStore metadata
#############################################################################
x-casaos:
  architectures: # Supported CPU architectures
    - amd64
    - arm
  main: kong # Main service of the application
  title: # Title of the application in English
    en_us: Supabase
  index: /
  port_map: "3001"

  developer: Supabase
  author: MobiWise
  category: MobiWise
  description:
    en_us: Supabase is an open-source alternative to Firebase, providing authentication, databases, storage, and serverless functions.
    fr_fr: Supabase est une alternative open-source à Firebase, offrant authentification, bases de données, stockage et fonctions serverless.
  icon: https://cdn.jsdelivr.net/gh/mobiwise-dev/big-bear-casaos-master/Apps/supabase/supabase-logo-icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mobiwise-dev/big-bear-casaos-master/Apps/supabase/supabase-thumbnail.png
    - https://cdn.jsdelivr.net/gh/mobiwise-dev/big-bear-casaos-master/Apps/supabase/supabase-table-editor.png
  tagline:
    en_us: Open-source alternative to Firebase
    fr_fr: Une alternative open-source à Firebase
  thumbnail: https://cdn.jsdelivr.net/gh/mobiwise-dev/big-bear-casaos-master/Apps/supabase/supabase-thumbnail.png
